language: r
warnings_are_errors: false

# blacklist
branches:
  except:
    - master

# whitelist
branches:
  only:
    - release

# covr
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
