##########################
#Summarise MCMCglmm data generated by hdr.mulTree function
##########################
#Creates a table containing the modes and the credibility intervals for the fixed and the random terms
#v0.2
#Update: removed the hdr calculations
##########################
#SYNTAX :
#<hdr.mcmc> a "hdr.mcmc" object (output from hdr.mulTree())
##########################
#----
#guillert(at)tcd.ie - 13/08/2014
##########################
#Requirements:
#-R 3
##########################


summary.mulTree<-function(hdr.mcmc)
{   #stop("IN DEVELOPEMENT")
    #warning("only works with uni-modal and hdr")
#HEADER


#DATA
    #hdr.mcmc
    if (class(hdr.mcmc) != "hdr.mcmc") {
        stop("Input is not a \"hdr.mcmc\" object.\nUse the hdr.mulTree function to generate the data.", call.=FALSE)
    } 

#FUNCTIONS

    FUN.sum.mcmc<-function(hdr.mcmc) {
        #Summarize the hdr.mcmc list building a table with the terms as rows and the estimates and the CI as columns
        #Preparing the columns
        terms<-names(hdr.mcmc)
        estimates<-rep(NA, length(terms)) ; lower.CI<-rep(NA, length(terms)) ; upper.CI<-rep(NA, length(terms))
        #Filling the columns
        for (n in 1:length(terms)) {
            estimates[n]<-hdr.mcmc[[n]]$mode
            lower.CI[n]<-min(hdr.mcmc[[n]]$hdr)
            upper.CI[n]<-max(hdr.mcmc[[n]]$hdr)
        }
        #Creating the data.frame
        sum.mcmc<-data.frame(row.names=terms, estimates=estimates, lower.CI=lower.CI, upper.CI=upper.CI)
        #Output
        return(sum.mcmc)
    }

#SUMMARIZYNG THE MCMC

    table<-FUN.sum.mcmc(hdr.mcmc)

#OUPTUT

    return(table)

#End
}
